### ISSUE TITLE
Regarding the status of downloading

### ISSUE THREAD

**Issue by ankmish** [luugiathuy/Java-Download-Manager#2]
After pasting a URL , its showing "Error" in status with output as 

File name: 227391
ERROR
ERROR
File size: -1
I had pasted the link "http://bossmobi.cc/files/download/type/128/id/227391"

What is  the problem ??
Plzz help

**Comment by cef1998** [comment]
![screenshot 60](https://user-images.githubusercontent.com/33161970/40983786-fc8eb1b8-68fd-11e8-91ac-5d1fded8d09e.png)

**Comment by IQooLogic** [comment]
If you enter this url to browser and hit enter HTTP response code is 301 (Moved permanently) then 302 (redirect) and then on this [http://bossmobi.fun/files/sfd455/227391/Jitni%20Dafa(bossmobi).mp3](link) you get 200 (OK)

The code test if response code is in 200 range and if it is then starts download if server supports Range header. 

This code does **NOT** support **redirects**! You have to add this functionalty. That is the problem you are having :)

**Comment by ankmish** [comment]
Thank you !!
Got my Mistake :)

**Comment by cef1998** [comment]
Solved.
